# Generated by Django 4.2.5 on 2023-10-15 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20231015_0054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actor',
            options={'managed': True},
        ),
    ]
